routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Exports\ProductsExport;
use Maatwebsite\Excel\Facades\Excel;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','WebController@home')->name('home');

Auth::routes();

Route::get('/logOut', function(){
	Auth::logout();
	return redirect()->route('home');
});

Route::get('/home', 'HomeController@index');

Route::get('/dashboard', 'HomeController@index');

Route::resource('/categories', 'CategoryController');

Route::resource('/sales', 'SaleController');

Route::resource('/stores', 'StoreController');

Route::resource('/products', 'ProductController');

Route::resource('/users', 'UserController');

Route::get('clients', 'UserController@clients');

Route::get('deliverys', 'UserController@deliverys');

Route::post('/import', 'ProductController@import');

Route::get('/details/{id}', 'StoreController@details');

Route::resource('/types', 'TypeController');

/**Listar tiendas por geoposicion */
Route::post('/tiendas', 'StoreController@geoList');

Route::get('/tiendas/categoria/{id}', 'StoreController@categoryList');

Route::get('/tiendas/tipo/{id}', 'StoreController@typeList');

Route::get('/acerca_nosotros','WebController@about');

Route::get('/terminos_y_condiciones','WebController@termsConditions');

Route::post('/contactMail', 'MailController@contactMail');

Route::post('/restorantRequestMail', 'MailController@restorantRequestMail');

Route::post('/deliveryRequestMail', 'MailController@deliveryRequestMail');

Route::get('/saleTest','SaleController@saleTest');

Route::post('/flowConfirm','SaleController@flowConfirm');

Route::post('/apiFlow','SaleController@confirm');

Route::post('/flowResult','SaleController@flowResult');

Route::resource('/contact','ContactController');

Route::get('/details/{id}/cart', 'StoreController@orderCart');

Route::get('/sale/{id}/payment', 'SaleController@orderPayment')->middleware('auth');

Route::get('/sale/{id}/pay', 'SaleController@goFlow')->middleware('auth');

Route::get('/sale/{id}/confirmed', 'SaleController@orderConfirmed');

Route::get('/sale/{id}/rejected', 'SaleController@orderRejected');

Route::get('/registro_restaurante','WebController@submitRestaurant');

Route::get('/testPy','WebController@testPy');

Route::get('/registro_repartidor','WebController@submitDriver');

Route::post('/sale/details', 'SaleController@detailCart');

Route::get('/perfil','WebController@perfil')->middleware('auth');

Route::get('/getDeliveryPrice/{distance}','WebController@getDeliveryPrice');

Route::get('/sales/{id}/invoice','SaleController@invoice');

Route::get('/mySales/{id}','SaleController@invoicePerfil');

resources/views/web/about.blade.php
@extends('layouts.web')

@section('content')

<!-- SubHeader =============================================== -->
<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="/web/images/banner2.png" data-natural-width="1400" data-natural-height="350">
    <div id="subheader">
    	<div id="sub_content">
    	 <h1>Acerca de Nosotros</h1>
         <p>Conoce nuestras metas y plan de integración al comercio comunal.</p>
         <p></p>
        </div><!-- End sub_content -->
	</div><!-- End subheader -->
</section><!-- End section -->
<!-- End SubHeader ============================================ -->

<!-- Content ================================================== -->
<div class="container margin_60_35">
	<div class="row">
		<div class="col-md-12 text-justify">
			<h3 class="nomargin_top">Algunas cosas sobre nosotros</h3>
			<p>Compra acá Spa nace en abril del 2020, prestando el servicio de transporte y delivery en todo el territorio nacional.
			</p>
			<p>
				Nuestro plan es ir generando distintas alianzas en cada localidad con los mejores locales comerciales y mercados de tu zona, para llevarte la gran variedad de productos y de la
				mejor calidad que se venden en tu comuna, con entrega en el momento, con los mismos valores como si fueras directo al local pero sin que te muevas de tu hogar. Tu solo pagas el
				servicio de delivery!!.
			</p>
			<h4>Nuestra Misión</h4>
			<p>
				Ofrecer a nuestros clientes los mejores productos y servicios de su mercado local logrando una relación de confianza y trasparencia con nuestros colaboradores, aliados y clientes,
				brindando un excelente servicio basado en la puntualidad y respeto de nuestro equipo humano y así entregar a nuestros clientes el mejor servicio de Delivery y pago de cuentas para
				hacer tu vida más simple y que disfrutes de tu tiempo.
			</p>
			<h4>Nuestra Visión</h4>
			<p>
				Consolidarnos cómo el mejor y más completo servicio de delivery de tu comuna a través de la satisfacción de nuestros clientes. Llegar a lugares remotos con el mejor del mercado
				local, contribuyendo al incremento del empleo. Ser reconocidos por clientes, proveedores, empleados como la mejor opción.
			</p>
		</div>
	
	</div><!-- End row -->
	<hr class="more_margin">
    <div class="main_title">
            <h2 class="nomargin_top">Por que comprar con nosotros?</h2>
            <p>
                Te llevamos lo mejor de tu comuna a la puerta de tu casa y acá tenemos muchas razones de porque preferirnos.
            </p>
        </div>
	<div class="row">
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
			<div class="feature">
				<i class="icon_building"></i>
				<h3><span>Los mejores</span> restaurantes</h3>
				<p>
					La mayor variedad de restaurantes y locales de tu comuna, diferentes opciones, según tus gustos y necesidades.
				</p>
			</div>
		</div>
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.2s">
			<div class="feature">
				<i class="icon_documents_alt"></i>
				<h3><span>+1000 tipos</span> de comidas</h3>
				<p>
					Menús variados, donde podrás elegir a tu gusto y conveniencia lo que quieres recibir en la puerta de tu casa.
				</p>
			</div>
		</div>
	</div><!-- End row -->
	<div class="row">
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.3s">
			<div class="feature">
				<i class="icon_bag_alt"></i>
				<h3><span>Envío o</span> para llevar</h3>
				<p>
					Tienes dos maneras de comprar en tus locales preferidos, delivery donde pagas tu pedido mas el valor de despacho y para llevar donde tu mismo retiras desde el local el pedido y solo pagas este.
				</p>
			</div>
		</div>
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.4s">
			<div class="feature">
				<i class="icon_mobile"></i>
				<h3><span>Soporte</span> en linea</h3>
				<p>
					Tenemos soporte en linea de 10am a 10pm todos los dias del año. Llamanos o contactate via whatsapp y te ayudamos a efectuar tus compras y solucionar tus dudas.
				</p>
			</div>
		</div>
	</div><!-- End row -->
	<div class="row">
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.5s">
			<div class="feature">
				<i class="icon_wallet"></i>
				<h3><span>Recibo</span> de efectivo</h3>
				<p>
					Si deseas pagar en efectivo, debes registrarte para poder comprar y tu pago debe ser justo, ya que nuestros repartidores no portan dinero para dar vuelto.
				</p>
			</div>
		</div>
		<div class="col-md-6 wow fadeIn" data-wow-delay="0.6s">
			<div class="feature">
				<i class="icon_creditcard"></i>
				<h3><span>Pago seguro</span> con tarjeta</h3>
				<p>
					Ocupamos sitema Flow, otra empresa nacional emprendedora donde podras ocupar cualquier tarjeta de creito o debito, onepay, webpay, servipag, mach y multicaja.
				</p>
			</div>
		</div>
	</div><!-- End row -->
</div><!-- End container -->

<div class="container-fluid">
	<div class="row">
		<div class="col-md-6 nopadding features-intro-img">
			<div class="features-bg">
				<div class="features-img">
					
				</div>
			</div>
		</div>
		<div class="col-md-6 nopadding">
			<div class="features-content">
				<h3>“YO ME QUEDO DISFRUTANDO”</h3>
				<p>
					Descarga la App y haz los pedidos desde tu casa, tu oficina, tu carrete o de donde estes!!
				</p>
				<p>
					Compras en los mejores locales de tu barrio, comida, cervezas, licores, carnes, carbon, pizzas, sushi, abarrotes, farmacia y todo lo que tu comuna vende nosotros te lo llevamos.
				</p>
				<p>
					Ya no te muevas de donde estas, sigue disfrutando y compartiendo sin ponerte en risego tu ni a los demas, dejanos eso a nosotros!!
				</p>
			</div>
		</div>
	</div>
</div><!-- End container-fluid  -->
<!-- End Content =============================================== -->
    
@endsection

resources/views/web/contact.blade.php
<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title" id="myModalLabel">Contacto</h2>
            </div>
            <form action="/contactMail" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group row">
                        <div class="col-md-6">
                            <input type="text" name="name" required class="form-control form-white" placeholder="Nombre">
                        </div>  
                        <div class="col-md-6">
                            <input type="email" name="email" required class="form-control form-white" placeholder="Email">
                        </div>   
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <input type="text" name="subject" required class="form-control form-white" placeholder="Asunto">
                        </div>    
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <textarea type="text" name="content" class="form-control form-white" required placeholder="Mensaje"></textarea>
                        </div>  
                    </div>
                </div>    
                <div class="modal-footer">	 
                    <div class="">
                        <button type="submit" class="btn btn-submit">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div><!-- End modal -->   

resources/views/web/detail_cart.blade.php
@extends('layouts.web')

@section('content')
<style>
	.disabledBtn {
		opacity: 0.3;
	}
</style>

<!-- SubHeader =============================================== -->
<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="/web/images/banner2.png" data-natural-width="1400" data-natural-height="350">
    <div id="subheader">
    	<div id="sub_content">
    	 <h1>Haga su Pedido</h1>
            <div class="bs-wizard">
                <div class="col-xs-4 bs-wizard-step active">
                  <div class="text-center bs-wizard-stepnum"><strong>1.</strong>Sus Datos</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="#0" class="bs-wizard-dot"></a>
                </div>
                               
                <div class="col-xs-4 bs-wizard-step disabled">
                  <div class="text-center bs-wizard-stepnum"><strong>2.</strong>Pago</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="cart_2.html" class="bs-wizard-dot"></a>
                </div>
            
              <div class="col-xs-4 bs-wizard-step disabled">
                  <div class="text-center bs-wizard-stepnum"><strong>3.</strong>Terminado!</div>
                  <div class="progress"><div class="progress-bar"></div></div>
                  <a href="cart_3.html" class="bs-wizard-dot"></a>
                </div>  
		</div><!-- End bs-wizard --> 
        </div><!-- End sub_content -->
	</div><!-- End subheader -->
</section><!-- End section -->
<!-- End SubHeader ============================================ -->


<!-- Content ================================================== -->
<div class="container margin_60_35">
		<div class="row">
			<form  id="goToPay" action="/sale/details" method="POST">
			<div class="col-md-3">
            
				<div class="box_style_2 hidden-xs info ">
					<h4 class="nomargin_top">Plazo de Entrega<i class="icon_clock_alt pull-right"></i></h4>
					<p>
						Tienda maneja un tiempo estimado de {{$sale->store->estimate_time ?? 30 }} min. Para entregar su pedido
					</p>
					<hr>
					
				</div><!-- End box_style_1 -->
				<div class="box_style_2 hidden-xs info ">
					<h4 class="nomargin_top">Login<i class=" pull-right"></i></h4>
					<p>
						Ya tienes una cuentra creada?
					</p>
					<p>
						Haz click aqui <a href="#0" data-toggle="modal" data-target="#login_2">Login</a>
					</p>
					<hr>
					
				</div><!-- End box_style_1 -->
                
				<div class="box_style_2 hidden-xs" id="help">
					<i class="icon_lifesaver"></i>
					<h4>Necesitas <span>Ayuda?</span></h4>
					<a href="tel://56988985377" class="phone">+569-8898-5377</a>
					<h5>Horario</h5>
					<small> 10:00 - 22:00</small>
				</div>
                
			</div><!-- End col-md-3 -->
				<div class="col-md-6">
					
						@csrf
						<input type="hidden" name="storeLat" value="{{$sale->store->lat}}">
						<input type="hidden" name="storeLng" value="{{$sale->store->lng}}">
						<input type="hidden" name="lat" id="lat">
						<input type="hidden" name="lng" id="lng">
						<div class="box_style_2" id="order_process">
							<h2 class="inner">Detalles de Usuario</h2>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label>Nombre</label>
									<input type="text" required class="form-control" name="f_name" {{ $user ? "readonly value=".$user->f_name." " : ''}}>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label>Apellido </label>
										<input type="text" required class="form-control" name="l_name" {{ $user ? "readonly value=".$user->l_name." " : ''}}>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label>Telefono/Movil</label>
										<input type="text" required name="tel_order" class="form-control"  {{ $user ? "readonly value=".$user->phone." " : ''}}>
									</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label>Email</label>
										<input type="email" required name="email_order" class="form-control"  {{ $user ? "readonly value=".$user->email." " : ''}}>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label>Rut</label>
										<input type="text" required name="rut" oninput="checkRut(this)" class="form-control"  {{ $user ? "readonly value=".$user->rut." " : ''}}>
									</div>
								</div>
								@if (!$user)
								<div class="col-md-6">
									<div class="form-group">
										<label>Password</label>
										<input type="password" required name="password" class="form-control" >
									</div>
								</div>
								@endif
								
							</div>
							<hr>
							<br>
							
						</div><!-- End box_style_1 -->
						<div class="box_style_2" id="order_process">
							<h2 class="inner">Detalles de su Pedido</h2>
							<div class="row">
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label>Direccion</label>
											<input type="text" id="pac-input" name="address" required class="form-control">
										</div>
									</div>
									<div class="col-md-12">
										<div id="map"></div>
									</div>							
								</div>	
								<hr>
								<div class="row">
									<div class="col-md-12">
											<label>Notas para el restaurante</label>
											<textarea class="form-control" style="height:150px" name="notes" id="notes"></textarea>
									</div>
								</div>
							</div>
						</div><!-- End box_style_1 -->

				</div><!-- End col-md-6 -->
			<div class="col-md-3" id="sidebar">
            	<div class="theiaStickySidebar">
				<div id="cart_box">
					<h3>Tu orden<i class="icon_cart_alt pull-right"></i></h3>
					<table class="table table_summary">
					<tbody id="cartTable">
						@foreach ($sale->saleitems as $item)
							<tr>
								<td>
								 <strong>{{$item->qty}}</strong> {{$item->product->name}}
								</td>
								<td>
									<strong class="pull-right">$ {{ $item->amount }}</strong>
								</td>
							</tr>
						@endforeach
					</tbody>
					</table>
					<hr>
					<div method="POST" >
					<table class="table table_summary">
					<tbody>
					<tr>
						<td>
							Subtotal <span id="subTotal" class="pull-right">$ {{ $sale->amount }}</span>
					   </td>
					</tr>
					<tr>
						<td>
							Valor Delivery<span id="deliverPrice" class="pull-right"></span>
						</td>
					</tr>
					<tr>
						<td class="total">
							 TOTAL <span class="pull-right" id="TotalPrice">$ {{ $sale->amount  }}</span>
						</td>
					</tr>
					</tbody>
					</table>
					<hr>

						<input type="hidden" name="store_id" value="{{$sale->store_id}}">
						<input type="hidden" name="sale_id" value="{{$sale->id}}">
						<input id="deliveryInput" type="hidden" name="delivery_price" value="">
				</div>
					<button type="submit" class="btn_full disabledBtn" disabled >Ir a pagar</button>
					
					<a class="btn_full_outline" href="/details/{{$sale->store_id}}"><i class="icon-right"></i>Añadir otros items</a>
				</div><!-- End cart_box -->
				</div><!-- End theiaStickySidebar -->
			</form>
			</div><!-- End col-md-3 -->
            
		</div><!-- End row -->
</div><!-- End container -->
<!-- End Content =============================================== -->

@endsection

@section('scripts')
    
<!-- SPECIFIC SCRIPTS -->
<script src="/web/js/ResizeSensor.min.js"></script>
<script src="/web/js/theia-sticky-sidebar.min.js"></script>
<script>
    jQuery('#sidebar').theiaStickySidebar({
      additionalMarginTop: 80
    });
</script>
<script src="/js/map-cart.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSY5xPLXVGwJ96DaIOn1CMqgJhMIqH89Q&libraries=places&callback=initMap" async defer></script>
<script src="/js/sales.js"></script>
<script src="/js/validarRUT.js"></script>
@endsection

resources/views/web/perfil.blade.php
@extends('layouts.web')

@section('css')

<!-- Bootstrap core CSS -->
<link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!--external css-->
<link href="/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
<!-- Custom styles for this template -->
<link href="/css/style.css" rel="stylesheet">
<link href="/css/style-responsive.css" rel="stylesheet">
    
@endsection

@section('content')

<!-- SubHeader =============================================== -->
<section class="parallax-window" id="short" data-parallax="scroll" data-image-src="/web/images/banner2.png" data-natural-width="1400" data-natural-height="350">
    <div id="subheader">
    	<div id="sub_content">
    	 <h1>Bienvenido {{$user->name}}</h1>
         <p></p>
        </div><!-- End sub_content -->
	</div><!-- End subheader -->
</section><!-- End section -->
<!-- End SubHeader ============================================ -->

   
<!-- Content ================================================== -->
<div class="container margin_60_35">
	<div class="row">   
        <div class="panel-heading">
            <ul class="nav nav-tabs nav-justified">
                <li class="active">
                    <a data-toggle="tab" href="#edit">Editar Perfil</a>
                </li>
                <li >
                    <a data-toggle="tab" href="#miscompras">Mis Compras</a>
                </li>
                
            </ul>
        </div>

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
	    @endif

        <div class="panel-body">
            <div class="tab-content">
                <div id="miscompras" class="tab-pane active">
                    <table class="table table-striped table-advance table-hover">
                        <h4><i class="fa fa-angle-right"></i> Mis Compras</h4>
                        <hr>
                        <thead>
                          <tr>
                            <th><i class="fa fa-shopping-cart"></i> Pedido</th>
                            <th><i class="fa fa-calendar"></i> Fecha</th>
                            <th><i class="fa fa-store"></i> Tienda</th>
                            <th class="hidden-phone"><i class="fa fa-money"></i> Precio</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                        @foreach ($user->sales as $s)
                          <tr>
                            <td>
                                {{$s->id}}
                            </td>
                            <td>
                                {{$s->created_at->toDateString()}}
                            </td>
                            <td>
                                {{$s->store->name}}
                            </td>
                            <td>
                                {{$s->amount}}
                            </td>
                            <td data-id="{{$s->id}}">   
                                <a class="btn btn-default" href="/mySales/{id}" style="background:transparent;padding: 0 12px" data-toggle="tooltip" data-placement="top" title="Mas info">
                                    <i class="fa fa-eye"></i>
                                </a>
                            </td>
                          </tr>
                        @endforeach  
                        </tbody>
                    </table>    
                </div> 
                <div id="edit"  class="tab-pane">
                    <h4 class="mb"><i class="fa fa-angle-right"></i> Editar Perfil</h4>
                        <form action="{{ route('users.update', $user->id) }}" class="form-horizontal style-form" method="POST">  
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Nombre</label>
                                <div class="col-sm-10">
                                    <input type="text" name="f_name" class="form-control" value="{{$user->f_name}}"> 
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Apellido</label>
                                <div class="col-sm-10">
                                    <input type="text" name="l_name" class="form-control" value="{{$user->l_name}}">
                                </div>
                            </div>    
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" name="email" class="form-control" value="{{$user->email}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Rut</label>
                                <div class="col-sm-10">
                                    <input type="text" name="rut" oninput="checkRut(this)" class="form-control" value="{{$user->rut}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Telefono</label>
                                <div class="col-sm-10">
                                    <input type="text" name="phone" class="form-control" value="{{$user->phone}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Direccion</label>
                                <div class="col-sm-10">
                                    <input type="text" name="address" class="form-control" value="{{$user->address}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 col-sm-2 control-label">Ciudad</label>
                                <div class="col-sm-10">
                                    <input type="text" name="city" class="form-control" value="{{$user->city}}">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                <input type="submit" value="Actualizar" class="btn btn-primary pull-right"  style="width:200px">
                                </div>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>

@include('admin.sales.info')		
    
@endsection

@section('scripts')
<script src="/lib/jquery/jquery.min.js"></script>
<script src="/lib/bootstrap/js/bootstrap.min.js"></script>
<script class="include" type="text/javascript" src="/lib/jquery.dcjqaccordion.2.7.js"></script>
<script src="/lib/jquery.scrollTo.min.js"></script>
<script src="/lib/jquery.nicescroll.js" type="text/javascript"></script>
<script src="/js/validarRUT.js"></script>

<script>
$(function(){
    $('body').on('click','.info',function(){
	var id = $(this).parent().data('id')
		$.get('/sales/'+id, function(r){
			$('#infoModal form').attr('action', "/sales/"+r.id)
			$('#infoModal input[name=nameUser]').val(r.user.f_name + r.user.l_name)
			$('#infoModal input[name=emailUser]').val(r.user.email)
			$('#infoModal input[name=phoneUser]').val(r.user.phone)
			$('#infoModal input[name=rutUser]').val(r.user.rut)
			$('#infoModal input[name=addressUser]').val(r.user.address)
			$('#infoModal input[name=nameStore]').val(r.store.name)
			$('#infoModal input[name=emailStore]').val(r.store.email)
			$('#infoModal input[name=addressStore]').val(r.store.address)
			$('#infoModal input[name=phoneStore]').val(r.store.phone)
			$('#infoModal input[name=hoursStore]').val(r.store.hours)
			$('#infoModal input[name=totalSale]').val(r.amount)
			$('#infoModal').modal()
		})
	})
		$("body").on('click', '.cancelEdit', function(e){
			e.preventDefault()
			location.reload()
	})
})
</script>
@endsection